### ISSUE TITLE
The "Solar Generation" layer is non-functioning

### ISSUE THREAD

**Issue by rYR79435** [openinframap/openinframap#122]
If you're reporting an issue with rendering, please provide:

### Screenshot
![20210926_17h46m24s_grim](https://user-images.githubusercontent.com/60985157/134814872-c29fc8d5-5548-4fd3-9e82-c9a55665b3fd.png)
### Link to where this issue occurs on OpenInfraMap
Everywhere

**Comment by rYR79435** [comment]
The GET requests for the Solar Generation `PBF` files return 404s. (`GET https://openinframap.org/heatmap/3/5/2.pbf`)

**Comment by russss** [comment]
Fixed now, not sure why that broke but it was an issue with the proxy config.

**Comment by rYR79435** [comment]
It still doesn't seem to work.
I can see that the requests don't 404 anymore, but the layer isn't showin up anyways.

I have tested in FF and Chrome.

**Comment by russss** [comment]
Aha yes, there was another issue which I've fixed now.

You may have to visit https://openinframap.org/heatmap.json and hard refresh for your browser to notice.
