### ISSUE TITLE
Pole/pylon/transformer icon rendering broken on mobile, and other style issues

### ISSUE THREAD

**Issue by PluMGMK** [openinframap/openinframap#170]
Hello! Since last week I've noticed that quite a few things suddenly seem "broken" on OpenInfraMap, and I haven't seen it mentioned anywhere yet, so here goes…

To illustrate, I'll use the example of [Kyletaun 38-kV Substation](https://www.openstreetmap.org/way/507582141) with its infobox shown, and the Layers menu open.

Firstly, here's what I get on Firefox for Android, which is what I use most often to browse OpenInfraMap:
![OIM_BadRender_Firefox_Android](https://github.com/openinframap/openinframap/assets/6503204/76e58535-037c-439d-b422-48efb524fd58)
The following issues are apparent:
* Layers menu layout incorrect
* Underscores in infobox, e.g. "Voltage_2" – never saw these until last week
* Poles and pylons on nearby power lines are not rendered.

My first check was to see if the same thing happens on the stock Android browser as opposed to Firefox, and this is what I get:
![OIM_BadRender_StockBrowser_Android](https://github.com/openinframap/openinframap/assets/6503204/235df7cf-b602-49a4-8b34-63f88474d549)
A bit better:
* Layers menu looks OK now, but the icon for it is still invisible
* Still have underscores in infobox
* Still no poles and pylons

So then I checked on my desktop, using luakit on Linux:
![OIM_BadRender_luakit_Linux](https://github.com/openinframap/openinframap/assets/6503204/c137c332-8f0f-4a4c-adaa-9cd88b466e33)
At least the poles and pylons are back now, but the underscores and invisible layers icon remain.

I suppose this could be caused by adblocking settings or something on my end, but this seems unlikely since I never use the Stock Android Browser, so it doesn't have any settings like that applied.

**Comment by russss** [comment]
Sorry about that, there was a deployment issue that I didn't catch. It should be fixed now.

**Comment by PluMGMK** [comment]
Sorry for the late response, but I'm afraid I'm still seeing the underscores, and the icons are still missing for me on mobile. The only thing that seems to be fixed is the layers icon…

**Comment by russss** [comment]
The icons are fixed now, sorry, there were two different issues there.

I am not sure what you mean by underscores, as I've changed how voltages are displayed now.

**Comment by PluMGMK** [comment]
Awesome, thanks! I see the new voltage display, it's pretty cool. But there are still underscores in tags like "Start_date". Or were those always there? 😅
